# Generated by Django 4.1.3 on 2022-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fruit_shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("desc", models.TextField()),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="picture")),
            ],
        ),
    ]
